version: '3.3'
services:
  php:
    build: './docker/php/'
    container_name: php
    volumes:
      - ./app/src/:/var/www/html/
    environment:
      DB_HOST: db:3306
      DB_USER: dbuser
      DB_PASSWORD: password
      DB_NAME: my_database
  apache:
    build: './docker/apache/'
    container_name: apache
    depends_on:
      - php
      - db
    ports:
      - "8080:80"
    volumes:
      - ./app/src/:/var/www/html/
  db:
    image: mysql:5.7
    container_name: mysql
    volumes:
     - db_data:/var/lib/mysql
     - ./docker/db/config/custom.cnf:/etc/mysql/conf.d/custom.cnf
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: my_database
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: password
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8282:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: password
volumes:
    db_data: {}